//
// Created by JIESOUL on 2019/9/16.
//

#ifndef C_CPP_LEARN_SRC_CPP_PRIMER_CH15_QUERYRESULT_H
#define C_CPP_LEARN_SRC_CPP_PRIMER_CH15_QUERYRESULT_H

class QueryResult {

};

#endif //C_CPP_LEARN_SRC_CPP_PRIMER_CH15_QUERYRESULT_H
