//
// Created by JIESOUL on 2019/9/25.
//

#ifndef C_CPP_LEARN_SRC_EFFECTIVE_CPP_EMPTY_H
#define C_CPP_LEARN_SRC_EFFECTIVE_CPP_EMPTY_H

class Empty {

};

#endif //C_CPP_LEARN_SRC_EFFECTIVE_CPP_EMPTY_H
